[project]
name = "portraits"
version = "0.1.0"
description = "Détection et recadrage de portraits"
requires-python = ">=3.10"
dependencies = [
    "opencv-python==4.10.0.84",
    "mediapipe==0.10.14",
    "Pillow==10.3.0",
    "numpy==1.26.4",
    "scikit-image==0.22.0",
    "python-dotenv==1.0.1",
]